#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 7352-web-01 44.200.66.174:80 check\n\tserver 7352-web-02 3.239.54.206:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
