#!/usr/bin/env bash
# uninstall mysql

sudo service mysql stop
sudo apt-get remove --purge mysql-server mysql-client mysql-common
sudo apt-get remove --purge mysql*
sudo apt-get purge mysql*
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt-get remove dbconfig-mysql
sudo rm -rf /var/lib/mysql
sudo apt-get dist-upgrade
