#!/usr/bin/env bash
# This script displays the content of the file
#+ /etc/passwd, using the while loop + IFS

while IFS=: read -r username passwd user_id group_id user_id_info home_dir shell; do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $passwd, more info about the user here: $user_id_info"
done < /etc/passwd
